#!/bin/bash

tail -20 /home/hamkahidayatullah/shell_script/bin/history
echo -n "Ketik pesan yang anda inginkan:"
read pesan

echo "$USER : $pesan" >> /home/hamkahidayatullah/shell_script/bin/history
tail -20 /home/hamkahidayatullah/shell_script/bin/history



