#!/bin/bash

echo -n "masukan password : "
read password

#Memasukan konidisi password agar sesuai
#1. password  minimum 8 karakter
#2. Minimal terdapat 1 huruf besar ,1 huruf kecil, dan 1 simbol
#3. Tidak boleh menggunakan username dari user
if [[ ${#password} -ge 8 && "$password" =~ [A-Z] && "$password" =~ [a-z] && "$password" =~ [0-9] && "$password" =~ [^A-Za-z0-9] && "$password" != 'whoami' ]]
then
	echo "Good Password"
else
	echo "Weak Password"
fi 
