#!/bin/bash

echo -n "masukan password : "
read password

if [[ "$password" != `whoami` && ${#password} -ge 8 && "$password" =~ [A-Z] && "$password" =~ [a-z] && "$password" =~ [0-9] && "$password" =~ [^A-Za-z0-9] ]]
then
	echo "Good Password"
else
	echo "Weak Password"
fi 
